"use client";
import {useEffect,useState} from 'react';
import {CAREER_KEY,emptyCareer,restoreCareer,importSelected,removeFact,selfPR,entrySheet,interview,exportCareer} from '../lib/career';
import type {CareerProfile,CareerFact} from '../lib/career';
import {MEMORY_KEY,restoreMemory} from '../lib/learningMemory';
import {PLANNER_KEY,restorePlanner} from '../lib/planner';
import {FeatureStatusBadge} from './AcademicShell';
export function CareerWorkspace(){
 const [p,setP]=useState<CareerProfile>(emptyCareer),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[candidates,setCandidates]=useState<CareerFact[]>([]),[selected,setSelected]=useState<string[]>([]),[factTitle,setFactTitle]=useState(''),[factDetail,setFactDetail]=useState(''),[kind,setKind]=useState<CareerFact['kind']>('user statement'),[skill,setSkill]=useState(''),[skillEvidence,setSkillEvidence]=useState(''),[output,setOutput]=useState<React.ReactNode>(null);
 useEffect(()=>{try{const saved=localStorage.getItem(CAREER_KEY);if(saved)setP(restoreCareer(JSON.parse(saved)));}catch{setError('Careerの保存内容を読み込めません。自動上書きしません。');}setReady(true);},[]);
 function change(next:CareerProfile){setP(next);setOutput(null);setNotice('変更は未保存です。');setError('');}
 function field(key:keyof CareerProfile,value:string|number){change({...p,[key]:value});}
 function attempt(action:()=>void){try{action();setError('');}catch(e){setError((e as Error).message);}}
 function choices(){attempt(()=>{const rows:CareerFact[]=[];const rawMemory=localStorage.getItem(MEMORY_KEY),rawPlanner=localStorage.getItem(PLANNER_KEY);
  if(rawMemory)for(const m of restoreMemory(JSON.parse(rawMemory)).items)rows.push({id:'memory:'+m.id,kind:'user statement',title:`${m.subject} / ${m.topic}`,detail:m.masteredItems||m.note,source:'Learning Memory / 学生自己申告・未検証',sourceId:m.id});
  if(rawPlanner){const planner=restorePlanner(JSON.parse(rawPlanner));for(const c of planner.classes)rows.push({id:'planner-course:'+c.id,kind:'course',title:c.name,detail:'Plannerに登録された授業。修得・成績は未確認。',source:'Planner / 学生登録・未検証',sourceId:c.id});for(const a of planner.assignments)rows.push({id:'planner-task:'+a.id,kind:'user statement',title:a.title,detail:`登録状態: ${a.status}。提出・成果は未検証。`,source:'Planner / 学生登録・未検証',sourceId:a.id});}
  setCandidates(rows);setSelected([]);setNotice('候補を表示しました。まだ取り込んでいません。選択してImport selected itemsを押してください。');});}
 function clear(){if(!confirm('Careerの保存内容・下書き・取り込みコピーだけを削除しますか？ 元のMemory/Plannerは変更しません。'))return;attempt(()=>{localStorage.removeItem(CAREER_KEY);setP(emptyCareer());setCandidates([]);setSelected([]);setFactTitle('');setFactDetail('');setSkill('');setSkillEvidence('');setOutput(null);setNotice('Careerをクリアしました。元のMemory/Plannerは保持されています。');});}
 const input=(key:keyof Pick<CareerProfile,'interests'|'courses'|'projects'|'research'|'activities'|'goals'|'strength'|'example'|'result'|'esQuestion'|'esFacts'|'interviewNotes'>,label:string)=><label key={key}>{label}<textarea aria-label={label} aria-describedby="career-errors" maxLength={6000} value={p[key]} onChange={e=>field(key,e.target.value)}/></label>;
 return <main className="workspace writing-workspace planner"><p className="eyebrow">15 / CAREER PREPARATION · STUDENT EVIDENCE</p><FeatureStatusBadge status="Foundation"/><h1>学んだことを、自分の言葉で。</h1><p className="intro-copy">実際の授業・経験・制作物から、就活準備の材料を整理する。</p><p className="shell-notice">Template / structured draft。AI生成ではありません。資格・GPA・役職・受賞・研究成果を補完しません。企業の文化・給与・採用情報は未検証。Official/verified source integration: NOT_IMPLEMENTED。</p><p>Local only / Save時だけCareer専用localStorageへ保存。API送信・応募・自動取り込みはOFFです。共有端末ではClearしてください。</p><p id="career-errors" role="alert">{error}</p><p role="status" aria-live="polite">{notice}</p>
 <fieldset disabled={!ready} className="writing-controls"><legend>Career profile（学生入力）</legend><div className="evidence-fields">{input('interests','関心分野')}{input('goals','Career goals')}{input('courses','実際の授業')}{input('projects','制作物・プロジェクト')}{input('research','研究')}{input('activities','アルバイト・サークル（任意）')}</div>
 <section className="evidence-section"><h2>選択した情報だけを取り込む</h2><button className="secondary-button" onClick={choices}>Memory / Plannerの候補を表示</button><p>候補表示はこの操作時だけ読み取り、選択しない情報はCareerへ取り込みません。</p>{candidates.map(c=><label key={c.id} className="consent-row"><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,c.id]:s.filter(id=>id!==c.id))}/>{c.title} — {c.source}</label>)}<button className="secondary-button" onClick={()=>attempt(()=>{change(importSelected(p,candidates,selected,true));setSelected([]);setNotice('選択項目を下書きへ取り込みました。Saveするまで未保存です。');})}>Import selected items</button></section>
 <section className="evidence-section"><h2>Evidenceとスキル</h2><label>Evidence種別<select aria-label="Evidence種別" value={kind} onChange={e=>setKind(e.target.value as CareerFact['kind'])}>{['user statement','course','project','research'].map(x=><option key={x}>{x}</option>)}</select></label><label>Evidenceタイトル<input aria-label="Evidenceタイトル" maxLength={6000} value={factTitle} aria-describedby="career-errors" onChange={e=>setFactTitle(e.target.value)}/></label><label>実際に確認できる内容<textarea maxLength={6000} value={factDetail} onChange={e=>setFactDetail(e.target.value)}/></label><button className="secondary-button" onClick={()=>attempt(()=>{change(restoreCareer({...p,facts:[...p.facts,{id:crypto.randomUUID(),kind,title:factTitle,detail:factDetail,source:'学生入力・未検証',sourceId:''}]}));setFactTitle('');setFactDetail('');})}>Evidenceを追加</button>
 <ul className="planner-list">{p.facts.map(f=><li key={f.id}><h3>{f.title}</h3><p>{f.detail}</p><p>{f.kind} / {f.source} / {f.sourceId||'manual'}</p><button className="secondary-button" aria-label={`${f.title}のEvidenceを削除`} onClick={()=>{change(removeFact(p,f.id));if(skillEvidence===f.id)setSkillEvidence('');}}>Evidenceを削除</button></li>)}</ul>
 <label>自分で確認したスキル<input aria-label="自分で確認したスキル" maxLength={6000} value={skill} onChange={e=>setSkill(e.target.value)} aria-describedby="career-errors"/></label><label>スキルのEvidence<select aria-label="スキルのEvidence" value={skillEvidence} onChange={e=>setSkillEvidence(e.target.value)}><option value="">根拠未入力（要確認）</option>{p.facts.map(f=><option key={f.id} value={f.id}>{f.title}</option>)}</select></label><button className="secondary-button" onClick={()=>attempt(()=>{change(restoreCareer({...p,skills:[...p.skills,{id:crypto.randomUUID(),name:skill,evidenceId:skillEvidence}]}));setSkill('');})}>スキルを追加</button><ul className="planner-list">{p.skills.map(s=><li key={s.id}>{s.name} — {p.facts.find(f=>f.id===s.evidenceId)?.title||'根拠未入力・未検証'} <button className="secondary-button" aria-label={`${s.name}を削除`} onClick={()=>change({...p,skills:p.skills.filter(x=>x.id!==s.id)})}>削除</button></li>)}</ul></section>
 <section className="evidence-section"><h2>自己PR / ES / 面接の準備</h2><label>自己PRのEvidence<select aria-label="自己PRのEvidence" value={p.prEvidenceId} onChange={e=>field('prEvidenceId',e.target.value)}><option value="">未選択</option>{p.facts.map(f=><option key={f.id} value={f.id}>{f.title}</option>)}</select></label>{input('strength','Strength（本人の言葉）')}{input('example','Example（実際の経験）')}{input('result','Result（確認できる結果だけ）')}<button className="secondary-button" onClick={()=>attempt(()=>{const r=selfPR(p);setOutput(<section aria-label="自己PR下書き"><h3>{r.status}</h3><dl><dt>Evidence</dt><dd>{r.evidence}</dd><dt>Strength</dt><dd>{r.strength}</dd><dt>Example</dt><dd>{r.example}</dd><dt>Result</dt><dd>{r.result}</dd></dl></section>);setNotice('自己PRの構造を表示しました。事実の検証や結果の補完はしていません。');})}>自己PRを整理</button>
 {input('esQuestion','ESの質問')}<label>ES文字数上限<input aria-label="ES文字数上限" type="number" min={1} max={10000} value={p.esLimit} aria-describedby="career-errors" onChange={e=>field('esLimit',Number(e.target.value))}/></label>{input('esFacts','ESに使う学生の事実')}<button className="secondary-button" onClick={()=>attempt(()=>{const r=entrySheet(p);setOutput(<section aria-label="ES下書き"><h3>{r.status}</h3><p>{r.question}</p><p style={{whiteSpace:'pre-wrap'}}>{r.text||'学生の事実を入力してください。'}</p><p>{r.characters}/{r.limit}文字 — {r.withinLimit?'上限内':'文字数超過'}</p><p>{r.missingEvidence?'Evidence未選択・要確認':'選択Evidenceは学生入力・未検証です。'}</p><p>{r.warning}</p></section>);setNotice('ESの文字数と入力事実を表示しました。');})}>ESを確認</button>
 {input('interviewNotes','面接の回答メモ')}<button className="secondary-button" onClick={()=>{const r=interview(p);setOutput(<section aria-label="面接準備"><h3>一般的な練習質問（企業の予測ではありません）</h3><ul>{r.questions.map(x=><li key={x}>{x}</li>)}</ul><p style={{whiteSpace:'pre-wrap'}}>{r.answerNotes||'回答メモ未入力'}</p><h3>Follow-up</h3><ul>{r.followUp.map(x=><li key={x}>{x}</li>)}</ul></section>);setNotice('面接練習の枠組みを表示しました。企業の選考情報ではありません。');}}>面接準備を整理</button></section>
 <div className="draft-actions"><button className="primary-button" onClick={()=>attempt(()=>{localStorage.setItem(CAREER_KEY,exportCareer(p));setNotice('Careerだけをこのブラウザーに保存しました。');})}>Save Career profile</button><button className="secondary-button" onClick={()=>attempt(()=>{const url=URL.createObjectURL(new Blob([exportCareer(p)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='unipilot-career.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('現在のCareer下書きをExportしました。保存や送信はしていません。');})}>Export Career</button><button className="secondary-button" onClick={clear}>Clear Career</button></div></fieldset>
 {output&&<div className="evidence-section">{output}</div>}
 </main>;
}
