"use client";
import {useState} from 'react';
import Link from 'next/link';
import {degreeAudit,fixtureRules} from '../lib/degree';
import type {CreditCourse} from '../lib/degree';
export function DegreeWorkspace(){
  const [courses,setCourses]=useState<CreditCourse[]>([]),[mode,setMode]=useState('fixture');
  let rules=fixtureRules();if(mode==='unknown')rules=rules.map(r=>({...r,fixture:false,source:{}}));if(mode==='conflict')rules[1]={...rules[1],ruleVersion:'fixture-v2'};
  const result=degreeAudit(rules,courses);
  return <main className="workspace writing-workspace calculator"><p className="eyebrow">07 / DEGREE · SCHEMA FOUNDATION</p><div className="planning-title"><h1>Course & Credit</h1><span className="feature-badge">Foundation</span></div>
    <div className="shell-notice">TEST UNIVERSITYの架空fixtureを使う規則エンジンの試作品です。実在大学の公式要件は未登録。卒業可否の判定・大学固有の助言はしません。</div><nav className="journey-nav"><Link href="/gpa">GPA Simulator ↗</Link><Link href="/sources">出典を確認 ↗</Link></nav>
    <section className="evidence-section"><h2>Rule identity / 規則の識別</h2><p>TEST UNIVERSITY / TEST FACULTY / TEST DEPARTMENT</p><p>Curriculum year:2026 · version:fixture-v1 · 有効期間:2026-04-01〜2030-03-31</p><p className="muted">Source: FICTITIOUS-TEST-ONLY。架空のTOTAL12・一般4・専門8単位です。これは大学公式要件でもVerified sourceでもありません。</p>
      <label>規則のデモ状態<select aria-label="規則のデモ状態" value={mode} onChange={e=>setMode(e.target.value)}><option value="fixture">架空fixtureの条件付き計算</option><option value="unknown">出典なし — Unknown</option><option value="conflict">Version競合 — 計算を停止</option></select></label></section>
    <section className="evidence-section"><h2>Credits / 入力単位</h2><p className="muted">この画面の入力はメモリー内のみ。再読み込みで失われ、サーバーへ送信されません。取得済み・算入対象だけを集計します。</p>
      {courses.map((c,i)=><fieldset key={c.id} className="evidence-entry"><legend>Course {i+1}</legend><div className="evidence-fields"><label>単位科目名 {i+1}<input aria-label={`単位科目名 ${i+1}`} maxLength={200} value={c.name} onChange={e=>setCourses(v=>v.map(x=>x.id===c.id?{...x,name:e.target.value}:x))}/></label><label>取得単位 {i+1}<input aria-label={`取得単位 ${i+1}`} aria-describedby="degree-status" type="number" min="0" max="1000" step="any" value={Number.isFinite(c.credits)?c.credits:''} onChange={e=>setCourses(v=>v.map(x=>x.id===c.id?{...x,credits:e.target.value===''?NaN:Number(e.target.value)}:x))}/></label><label>区分 {i+1}<select aria-label={`区分 ${i+1}`} value={c.category} onChange={e=>setCourses(v=>v.map(x=>x.id===c.id?{...x,category:e.target.value}:x))}><option>一般</option><option>専門</option></select></label><label className="evidence-checkbox"><input type="checkbox" checked={c.completed} onChange={e=>setCourses(v=>v.map(x=>x.id===c.id?{...x,completed:e.target.checked}:x))}/>取得済み {i+1}</label><label className="evidence-checkbox"><input type="checkbox" checked={c.included} onChange={e=>setCourses(v=>v.map(x=>x.id===c.id?{...x,included:e.target.checked}:x))}/>単位算入 {i+1}</label></div><button className="secondary-button" onClick={()=>setCourses(v=>v.filter(x=>x.id!==c.id))}>単位科目を削除 {i+1}</button></fieldset>)}
      <button className="secondary-button" disabled={courses.length>=100} onClick={()=>setCourses(v=>[...v,{id:crypto.randomUUID(),name:'',credits:0,category:'一般',completed:true,included:true}])}>単位科目を追加</button><button className="secondary-button" onClick={()=>{if(confirm('この画面の単位入力を削除しますか？'))setCourses([]);}}>Clear credits</button></section>
    <section className="evidence-section" aria-live="polite"><h2>Conditional credit audit</h2><p id="degree-status" role="status">{result.status}: {result.reason}</p><p>Total credits: <strong data-testid="degree-total">{result.totalCredits}</strong></p>
      <div className="calc-table"><table><caption>取得済み区分単位（入力の単純集計）</caption><thead><tr><th scope="col">区分</th><th scope="col">取得済み</th></tr></thead><tbody>{Object.entries(result.categoryCredits).map(([category,credits])=><tr key={category}><th scope="row">{category}</th><td>{credits}</td></tr>)}</tbody></table></div>
      {!!result.requirements.length&&<div className="calc-table"><table><caption>架空fixtureの残り単位（卒業判定ではありません）</caption><thead><tr><th scope="col">区分</th><th scope="col">必要</th><th scope="col">取得</th><th scope="col">残り</th></tr></thead><tbody>{result.requirements.map(r=><tr key={r.category}><th scope="row">{r.category}</th><td>{r.required}</td><td>{r.earned}</td><td>{r.remaining}</td></tr>)}</tbody></table></div>}
    </section></main>;
}
