"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {calculateGpa,emptyGpa,exportGpa,restoreGpa,targetGpa,whatIf} from '../lib/gpa';
import type {GpaDraft,RetakeMode} from '../lib/gpa';
const KEY='unipilot-gpa-v1';
const display=(n:number|null)=>n===null?'—':n.toFixed(3);
export function GpaWorkspace(){
  const [draft,setDraft]=useState<GpaDraft>(emptyGpa),[ready,setReady]=useState(false),[notice,setNotice]=useState('');
  useEffect(()=>{try{const saved=sessionStorage.getItem(KEY);if(saved)setDraft(restoreGpa(JSON.parse(saved)));}catch{setNotice('保存データを読み込めません。自動で上書きしません。Clearまたは手動保存を選んでください。');}setReady(true);},[]);
  const current=calculateGpa(draft.policy,draft.courses),scenario=whatIf(draft.policy,draft.courses,draft.scenario);
  const maximum=Math.max(0,...draft.policy.grades.filter(g=>g.included).map(g=>g.points));
  const target=targetGpa(current.qualityPoints,current.credits,draft.futureCredits,draft.target,maximum);
  const errors=[...current.errors,...scenario.errors,...(target.error?[target.error]:[])];const invalid=errors.length>0;
  function save(){try{sessionStorage.setItem(KEY,JSON.stringify(draft));setNotice('GPA下書きをこのタブに保存しました。');}catch{setNotice('保存できません。JSON exportでローカルに保管してください。');}}
  function clear(){if(!confirm('GPAの入力・保存データを削除しますか？'))return;try{sessionStorage.removeItem(KEY);setDraft(emptyGpa());setNotice('GPAの入力・保存データを削除しました。');}catch{setNotice('保存データを削除できません。ブラウザーのサイトデータ設定を確認してください。');}}
  function download(){const url=URL.createObjectURL(new Blob([exportGpa(draft)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='unipilot-gpa.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('JSONをローカル生成しました。外部送信はありません。');}
  const policy=draft.policy;
  return <main className="workspace writing-workspace calculator"><p className="eyebrow">08 / GPA · GENERIC BETA</p><div className="planning-title"><h1>GPA Simulator</h1><span className="feature-badge status-beta">Beta</span></div>
    <p className="intro-copy">入力した単位と評価基準から、現在と「もしも」を計算する。</p><div className="shell-notice">特定大学の公式制度ではありません。計算は決定論的コードのみ・LLM不使用。再履修・除外・丸めの正式な規則は所属大学で確認してください。</div>
    <nav className="journey-nav" aria-label="GPA sections"><a href="#gpa-courses">科目入力</a><a href="#gpa-result">計算結果</a><a href="#gpa-target">目標GPA</a><Link href="/degree">履修・単位の基盤 ↗</Link></nav>
    <fieldset disabled={!ready} className="writing-controls"><legend className="sr-only">GPA editor</legend>
      <section className="evidence-section"><h2>Grading policy / 自分の評価基準</h2><label>方針名<input maxLength={200} aria-label="方針名" value={policy.name} onChange={e=>setDraft(d=>({...d,policy:{...d.policy,name:e.target.value}}))}/></label>
        <p className="muted">初期値A=4等は編集可能な例です。単位は各科目で入力します。評価区分の除外と科目の除外は別に扱います。</p>
        <div className="policy-grades">{policy.grades.map((g,i)=><fieldset key={g.id} className="grade-policy"><legend>評価 {i+1}</legend><label>評価ラベル {i+1}<input aria-label={`評価ラベル ${i+1}`} maxLength={60} value={g.label} onChange={e=>setDraft(d=>({...d,policy:{...d.policy,grades:d.policy.grades.map(x=>x.id===g.id?{...x,label:e.target.value}:x)}}))}/></label><label>Grade points {i+1}<input aria-label={`Grade points ${i+1}`} type="number" min="0" max="100" step="any" aria-describedby="gpa-errors" value={Number.isFinite(g.points)?g.points:''} onChange={e=>setDraft(d=>({...d,policy:{...d.policy,grades:d.policy.grades.map(x=>x.id===g.id?{...x,points:e.target.value===''?NaN:Number(e.target.value)}:x)}}))}/></label><label className="evidence-checkbox"><input type="checkbox" checked={g.included} onChange={e=>setDraft(d=>({...d,policy:{...d.policy,grades:d.policy.grades.map(x=>x.id===g.id?{...x,included:e.target.checked}:x)}}))}/>評価 {i+1} をGPA算入</label></fieldset>)}</div>
        <button className="secondary-button" disabled={policy.grades.length>=30} onClick={()=>setDraft(d=>({...d,policy:{...d.policy,grades:[...d.policy.grades,{id:crypto.randomUUID(),label:'新しい評価',points:0,included:true}]}}))}>評価区分を追加</button>
        <label>再履修方針<select aria-label="再履修方針" value={policy.retakeMode} onChange={e=>setDraft(d=>({...d,policy:{...d.policy,retakeMode:e.target.value as RetakeMode}}))}><option value="both">Count both / 両方算入</option><option value="replace">Replace old grade / 同じ単位数の旧成績を置換</option><option value="exclude-old">Exclude old / 旧科目を除外し新単位数を使用</option></select></label>
        <p className="muted">置換・旧科目除外では再履修元は算入されません。最新科目を手動除外しても旧科目は復活しません。Replaceは単位数一致が必要です。大学公式規則ではなく、このツールの明示的な仮定です。</p>
        <label>Policy rounding<select aria-label="Policy rounding" value={policy.rounding?.mode||'none'} onChange={e=>setDraft(d=>({...d,policy:{...d.policy,rounding:e.target.value==='none'?undefined:{digits:2,mode:e.target.value==='floor'?'floor':'nearest'}}}))}><option value="none">なし（内部の未丸め値を使用）</option><option value="nearest">小数2桁・四捨五入</option><option value="floor">小数2桁・切り捨て</option></select></label>
      </section>
      <section className="evidence-section" id="gpa-courses"><h2>Courses / 科目</h2><p className="muted">最大100件。0単位・除外科目は分母に入りません。What-ifは実際の成績を変更しません。</p>
        {draft.courses.map((c,i)=><fieldset key={c.id} className="evidence-entry"><legend>Course {i+1}</legend><div className="evidence-fields"><label>科目名 {i+1}<input aria-label={`科目名 ${i+1}`} maxLength={200} value={c.name} onChange={e=>setDraft(d=>({...d,courses:d.courses.map(x=>x.id===c.id?{...x,name:e.target.value}:x)}))}/></label><label>単位 {i+1}<input aria-label={`単位 ${i+1}`} type="number" min="0" max="1000" step="any" aria-describedby="gpa-errors" value={Number.isFinite(c.credits)?c.credits:''} onChange={e=>setDraft(d=>({...d,courses:d.courses.map(x=>x.id===c.id?{...x,credits:e.target.value===''?NaN:Number(e.target.value)}:x)}))}/></label>
          <label>成績 {i+1}<select aria-label={`成績 ${i+1}`} value={c.grade} onChange={e=>setDraft(d=>({...d,courses:d.courses.map(x=>x.id===c.id?{...x,grade:e.target.value}:x)}))}>{policy.grades.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label><label>What-if 成績 {i+1}<select aria-label={`What-if 成績 ${i+1}`} value={draft.scenario[c.id]||''} onChange={e=>setDraft(d=>({...d,scenario:{...d.scenario,[c.id]:e.target.value}}))}><option value="">現在の成績</option>{policy.grades.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label>
          <label>再履修元 {i+1}<select aria-label={`再履修元 ${i+1}`} aria-describedby="gpa-errors" value={c.retakeOf||''} onChange={e=>setDraft(d=>({...d,courses:d.courses.map(x=>x.id===c.id?{...x,retakeOf:e.target.value||undefined}:x)}))}><option value="">なし</option>{c.retakeOf&&!draft.courses.some(x=>x.id===c.retakeOf)&&<option value={c.retakeOf}>参照先削除済み・要修正</option>}{draft.courses.filter(x=>x.id!==c.id).map(x=><option key={x.id} value={x.id}>{x.name||'科目名未入力'}</option>)}</select></label><label className="evidence-checkbox"><input type="checkbox" checked={c.included} onChange={e=>setDraft(d=>({...d,courses:d.courses.map(x=>x.id===c.id?{...x,included:e.target.checked}:x)}))}/>科目 {i+1} を算入</label></div>
          <button className="secondary-button" onClick={()=>setDraft(d=>{const scenario={...d.scenario};delete scenario[c.id];return {...d,scenario,courses:d.courses.filter(x=>x.id!==c.id)};})}>科目を削除 {i+1}</button></fieldset>)}
        <button className="secondary-button" disabled={draft.courses.length>=100} onClick={()=>setDraft(d=>({...d,courses:[...d.courses,{id:crypto.randomUUID(),name:'',credits:0,grade:d.policy.grades[0].id,included:true}]}))}>科目を追加</button>
      </section>
      <section className="evidence-section" id="gpa-result" aria-live="polite"><h2>Current GPA / What-if</h2><div id="gpa-errors" role="status">{[...new Set(errors)].map(error=><p className="calc-error" key={error}>{error}</p>)}</div>
        {invalid?<p>入力を修正するまで結果を表示しません。</p>:<><div className="calculation-results"><p>Current GPA<strong data-testid="current-gpa">{display(current.rawGpa)}</strong></p><p>What-if GPA<strong data-testid="whatif-gpa">{display(scenario.rawGpa)}</strong></p><p>Policy rounded<strong>{display(current.policyGpa)}</strong></p></div><p>Quality points: {current.qualityPoints} / GPA credits: {current.credits}</p><p className="muted">表示は小数3桁。内部集計・目標計算に早期丸めを使いません。分母0の場合はGPA未定義（—）です。</p>
          <div className="calc-table"><table><caption>算入判定の内訳（現在の成績）</caption><thead><tr><th scope="col">科目</th><th scope="col">単位</th><th scope="col">評価</th><th scope="col">判定</th></tr></thead><tbody>{current.rows.map(r=><tr key={r.id}><th scope="row">{r.name||'未入力'}</th><td>{r.credits}</td><td>{r.gradeLabel} ({r.points})</td><td>{r.reason}</td></tr>)}</tbody></table></div></>}
      </section>
      <section className="evidence-section" id="gpa-target"><h2>Target GPA / 目標</h2><div className="evidence-fields"><label>目標GPA<input aria-label="目標GPA" type="number" min="0" max="100" step="any" aria-describedby="gpa-errors" value={Number.isFinite(draft.target)?draft.target:''} onChange={e=>setDraft(d=>({...d,target:e.target.value===''?NaN:Number(e.target.value)}))}/></label><label>今後のGPA算入単位<input aria-label="今後のGPA算入単位" type="number" min="0" max="100000" step="any" aria-describedby="gpa-errors" value={Number.isFinite(draft.futureCredits)?draft.futureCredits:''} onChange={e=>setDraft(d=>({...d,futureCredits:e.target.value===''?NaN:Number(e.target.value)}))}/></label></div>
        <div role="status" aria-live="polite">{!invalid&&<><p>必要な将来平均grade points: <strong data-testid="required-average">{display(target.requiredAverage)}</strong>（このpolicyの上限 {maximum}）</p><p>{target.status==='IMPOSSIBLE'?'Impossible under current policy':target.status==='TARGET_ALREADY_ACHIEVED'?'Target already achieved（今後の単位0）':target.status==='TARGET_ALREADY_FUNDED'?'今後の平均0でも目標以上です':target.status==='NO_FUTURE_CREDITS'?'今後の単位を入力してください。分母0では計算しません。':'入力した仮定の範囲では達成可能です。保証ではありません。'}</p></>}</div><p className="muted">(目標 × (現在のGPA単位 + 今後の単位) − 現在のquality points) ÷ 今後の単位。再履修による将来の分母変更は含みません。What-ifではなく現在値から計算します。</p>
      </section><div className="draft-actions"><button className="primary-button" disabled={invalid} onClick={save}>GPAをこのタブに保存</button><button className="secondary-button" disabled={invalid} onClick={download}>JSON export</button><button className="secondary-button" onClick={clear}>Clear GPA</button></div></fieldset><p role="status" aria-live="polite">{notice}</p>
  </main>;
}
