"use client";
import {useState} from 'react';
import {searchOfficialFixtures} from '../lib/officialSources';
import type {OfficialResult} from '../lib/officialSources';
import {FeatureStatusBadge} from './AcademicShell';
export function OfficialSearchWorkspace(){
  const [query,setQuery]=useState(''),[year,setYear]=useState('2026'),[results,setResults]=useState<OfficialResult[]|null>(null),[error,setError]=useState('');
  return <main className="workspace writing-workspace planner"><p className="eyebrow">14 / OFFICIAL UNIVERSITY INFORMATION · DEMO CONTRACT</p><FeatureStatusBadge status="Foundation"/><h1>公式情報を、根拠とともに。</h1><p className="intro-copy">出典・年度・確認日を分けて見る。</p><p className="shell-notice">架空のTEST UNIVERSITYだけを検索するローカルDemoです。Live検索は未実装・未検証。実在大学の期限・単位・採点の回答には使えません。外部AI API: OFF。</p>
  <form noValidate onSubmit={e=>{e.preventDefault();if(!query.trim()||!/^\d{4}$/.test(year)){setError('検索語と4桁の年度を入力してください。');setResults(null);return;}setError('');setResults(searchOfficialFixtures(query,year,new Date().toISOString().slice(0,10)));}}><fieldset className="writing-controls"><legend>登録済みの公式sourceを確認</legend><p>大学: TEST UNIVERSITY（架空） / 登録domain: official.unipilot.example / subdomain許可: NO</p><div className="evidence-fields"><label>検索語<input maxLength={200} value={query} aria-invalid={!!error} aria-describedby="official-error official-examples" onChange={e=>{setQuery(e.target.value);setResults(null);setError('');}}/></label><label>対象年度<input maxLength={4} inputMode="numeric" value={year} aria-invalid={!!error} aria-describedby="official-error" onChange={e=>{setYear(e.target.value);setResults(null);setError('');}}/></label></div><p id="official-examples">Demo例: 履修 / 奨学金 / 試験 / 期限 / 教室 / 非公式</p><p id="official-error" role="alert">{error}</p><button className="primary-button" type="submit">Demo sourceを検索</button></fieldset></form>
  <p role="status" aria-live="polite">{results?`${results.length}件の確認結果。根拠不足や矛盾があれば推測で統合しません。`:''}</p>
  {results&&<section className="evidence-section" aria-label="公式source確認結果"><h2>確認結果 — DEMO ONLY</h2><ul className="planner-list">{results.map((r,i)=><li key={r.source?.id||i}><h3>{r.source?.title||'該当する根拠なし'}</h3><strong>{r.status}</strong><p>{r.reason}</p><dl><dt>academic_year</dt><dd>{r.source?.academicYear||'Unknown'}</dd><dt>last_verified_at</dt><dd>{r.source?.lastVerifiedAt||'Unknown'}</dd><dt>effective_date</dt><dd>{r.source?.effectiveDate||'Unknown'}</dd><dt>Source / domain</dt><dd>{r.source?.university||'Unknown'} / {r.source?.domain||'Unknown'}</dd><dt>URL（架空・接続しません）</dt><dd>{r.source?.url||'Unknown'}</dd><dt>利用条件</dt><dd>{r.source?.termsNote||'Unknown'}</dd><dt>Evidence span</dt><dd>{r.evidence?.span||'取得された根拠がありません。公式窓口に確認してください。'}</dd><dt>Citation Engine status</dt><dd>{r.citation?.status||'Needs verification'} — 実在sourceの真正性をVerifiedへ昇格しません。</dd></dl></li>)}</ul><p>Today・Memory・Planへの追加や自動保存はありません。</p></section>}
  </main>;
}
