"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {EvidenceLedger} from "./EvidenceLedger";
import {bibliography,emptyDraft,linkedEvidence,removeEvidence,restoreDraft} from "../lib/evidence";
import type {PlanningDraft,Requirement} from "../lib/evidence";

const labels={report:["テーマ","課題文","文字数","締切","レポート形式","引用形式","教授からの条件","参考資料"],research:["研究テーマ","研究質問","Purpose / 研究目的","Hypothesis / 仮説（任意）","Method / 研究方法","Analysis Notes / 分析メモ","Limitations / 限界","方法・分析のメモ","先行研究・参考資料","結果・考察のメモ"]};
export function PlanningWorkspace({kind}:{kind:"report"|"research"}) {
  const [draft,setDraft]=useState<PlanningDraft>(emptyDraft),[ready,setReady]=useState(false),[notice,setNotice]=useState('');
  const key=`unipilot-${kind}-draft-v2`,oldKey=`unipilot-${kind}-draft-v1`;
  useEffect(()=>{setReady(false);try{const saved=sessionStorage.getItem(key);const restored=saved?restoreDraft(JSON.parse(saved)):restoreDraft({values:JSON.parse(sessionStorage.getItem(oldKey)||'{}')});restored.values=Object.fromEntries(Object.entries(restored.values).filter(([k])=>labels[kind].includes(k)));setDraft(restored);setNotice('入力はサーバーへ送信されません。「このタブに保存」で保存してください。');}catch{setDraft(emptyDraft());setNotice('保存データを読み込めませんでした。自動では上書きしません。');}setReady(true);},[key,oldKey,kind]);
  function save(){try{sessionStorage.setItem(key,JSON.stringify(draft));setNotice('このタブに下書きを保存しました。タブを閉じると失われます。');}catch{setNotice('保存できませんでした。入力メモをコピーして保管してください。');}}
  function clear(){if(!window.confirm('このWorkspaceの入力と保存データをすべて削除しますか？'))return;try{sessionStorage.removeItem(key);sessionStorage.removeItem(oldKey);setDraft(emptyDraft());setNotice('このWorkspaceの入力と保存データを削除しました。');}catch{setNotice('保存データを削除できませんでした。ブラウザーのサイトデータ設定を確認してください。');}}
  async function copy(){try{await navigator.clipboard.writeText(JSON.stringify(draft,null,2));setNotice('入力メモ・根拠・主張の構造をコピーしました。');}catch{setNotice('コピーできませんでした。入力欄のテキストを選択してください。');}}
  return <main className="workspace writing-workspace"><p className="eyebrow">{kind==='report'?'03 / REPORT':'04 / RESEARCH'} · STAGE 3 / FOUNDATION</p><div className="planning-title"><h1>{kind==='report'?'Report Workspace':'Research Workspace'}</h1><span className="feature-badge">Foundation</span></div><p className="intro-copy">{kind==='report'?'条件を整理し、根拠から自分の論を組み立てる。':'一つの問いと、確かめられる根拠をつなぐ。'}</p>
    <div className="shell-notice">入力・文献メモ・根拠の整理を支援します。全文自動執筆・論文検索・外部検証は行いません。AI要約も原文の根拠ではありません。</div>
    <nav className="journey-nav" aria-label="Workspace sections"><a href="#requirements">{kind==='report'?'課題の条件':'研究の問い'}</a><a href="#evidence-heading">根拠</a><a href="#claims-heading">主張と引用</a><a href="#outline-heading">Outline</a>{kind==='research'&&<a href="#literature-heading">Literature Notes</a>}</nav>
    <fieldset disabled={!ready} className="writing-controls"><legend className="sr-only">{kind} draft editor</legend><section className="planning-form" id="requirements"><h2>{kind==='report'?'Requirements / 課題の条件':'Research Question / 研究の設計'}</h2><p className="muted">入力した条件だけを扱います。不明な内容は空欄のまま残せます。</p><div className="evidence-fields">
      {labels[kind].map(label=><label key={label} className={label==='課題文'?'wide-field':''}>{label}{label==='締切'?<input type="date" aria-label={label} value={draft.values[label]||''} onChange={e=>setDraft(d=>({...d,values:{...d.values,[label]:e.target.value}}))}/>:<textarea rows={label==='課題文'?4:2} maxLength={20000} aria-label={label} value={draft.values[label]||''} onChange={e=>setDraft(d=>({...d,values:{...d.values,[label]:e.target.value}}))}/>}</label>)}</div>
      {kind==='report'&&<section className="writing-subsection"><h3>Requirement checklist</h3><p className="muted">学生自身が確認する条件です。自動で条件を補完しません。</p>{draft.requirements.map((r,i)=><div key={r.id} className="checklist-row"><label>条件 {i+1}<input aria-label={`条件 ${i+1}`} maxLength={20000} value={r.text} onChange={e=>setDraft(d=>({...d,requirements:d.requirements.map(x=>x.id===r.id?{...x,text:e.target.value}:x)}))}/></label><label>確認状態 {i+1}<select aria-label={`確認状態 ${i+1}`} value={r.state} onChange={e=>setDraft(d=>({...d,requirements:d.requirements.map(x=>x.id===r.id?{...x,state:e.target.value as Requirement['state']}:x)}))}>{['必須条件','未確認条件','確認済み'].map(v=><option key={v}>{v}</option>)}</select></label><button className="secondary-button" onClick={()=>setDraft(d=>({...d,requirements:d.requirements.filter(x=>x.id!==r.id)}))}>条件を削除 {i+1}</button></div>)}<button className="secondary-button" disabled={draft.requirements.length>=40} onClick={()=>setDraft(d=>({...d,requirements:[...d.requirements,{id:crypto.randomUUID(),text:'',state:'未確認条件'}]}))}>条件を追加</button></section>}
    </section><EvidenceLedger items={draft.evidence} onChange={evidence=>setDraft(d=>({...d,evidence}))} onDelete={id=>setDraft(d=>removeEvidence(d,id))}/>
    <section className="evidence-section" aria-labelledby="claims-heading"><p className="eyebrow">CLAIM → EVIDENCE → SPAN → METADATA</p><h2 id="claims-heading">Claim–Evidence Trace</h2><p className="muted">関連付けは支持の正しさを検証しません。引用箇所と主張の関係を自分で確認してください。</p>
      {draft.claims.map((claim,i)=>{const linked=linkedEvidence(claim,draft.evidence);return <fieldset className="evidence-entry" key={claim.id}><legend>Claim {i+1}</legend><label>主張 {i+1}<textarea aria-label={`主張 ${i+1}`} maxLength={20000} value={claim.text} onChange={e=>setDraft(d=>({...d,claims:d.claims.map(c=>c.id===claim.id?{...c,text:e.target.value}:c)}))}/></label><p className="evidence-status">{linked.length?`${linked.length}件の根拠を関連付け済み（支持は未検証）`:'Unsupported — 根拠が関連付けられていません'}</p>
        {draft.evidence.map((entry,j)=><label className="evidence-checkbox" key={entry.id}><input type="checkbox" checked={claim.evidenceIds.includes(entry.id)} onChange={e=>setDraft(d=>({...d,claims:d.claims.map(c=>c.id===claim.id?{...c,evidenceIds:e.target.checked?[...c.evidenceIds,entry.id]:c.evidenceIds.filter(id=>id!==entry.id)}:c)}))}/>{`Claim ${i+1} → Evidence ${j+1}: ${entry.title||'資料名未入力'}`}</label>)}
        {linked.map(entry=><div className="citation-trace" key={entry.id}><h3>{entry.title||'資料名未入力'} — {entry.status}</h3><blockquote>{entry.span||'Exact span 未入力'}</blockquote><p>{bibliography(entry).text||'Metadata 未入力'}</p><p className="muted">不足項目: {bibliography(entry).missing.join(', ')||'表示項目は入力済み（未検証）'}</p></div>)}<button className="secondary-button" onClick={()=>setDraft(d=>({...d,claims:d.claims.filter(c=>c.id!==claim.id)}))}>主張を削除 {i+1}</button></fieldset>;})}<button className="secondary-button" disabled={draft.claims.length>=40} onClick={()=>setDraft(d=>({...d,claims:[...d.claims,{id:crypto.randomUUID(),text:'',evidenceIds:[]}]}))}>主張を追加</button></section>
    {kind==='research'&&<section className="evidence-section" aria-labelledby="literature-heading"><h2 id="literature-heading">Literature Notes</h2><p className="muted">資料のmetadataと原文はEvidence Ledgerに保存。ここでは要約の作成者と研究質問を分離して記録します。</p>
      {draft.literature.map((note,i)=>{const source=draft.evidence.find(e=>e.id===note.evidenceId);return <fieldset key={note.id} className="evidence-entry"><legend>Literature {i+1}</legend><label>文献の根拠 {i+1}<select aria-label={`文献の根拠 ${i+1}`} value={note.evidenceId} onChange={e=>setDraft(d=>({...d,literature:d.literature.map(n=>n.id===note.id?{...n,evidenceId:e.target.value}:n)}))}><option value="">未指定</option>{draft.evidence.map((e,j)=><option key={e.id} value={e.id}>{j+1}: {e.title||'資料名未入力'}</option>)}</select></label>
        <label>要約の作成者 {i+1}<select aria-label={`要約の作成者 ${i+1}`} value={note.provenance} onChange={e=>setDraft(d=>({...d,literature:d.literature.map(n=>n.id===note.id?{...n,provenance:e.target.value==='AI'?'AI':'Student'}:n)}))}><option>Student</option><option>AI</option></select></label>
        <label>Source summary {i+1}（原文の根拠ではありません）<textarea aria-label={`Source summary ${i+1}`} maxLength={20000} rows={4} value={note.summary} onChange={e=>setDraft(d=>({...d,literature:d.literature.map(n=>n.id===note.id?{...n,summary:e.target.value}:n)}))}/></label><label>Related Research Question {i+1}<textarea aria-label={`Related Research Question ${i+1}`} maxLength={20000} value={note.question} onChange={e=>setDraft(d=>({...d,literature:d.literature.map(n=>n.id===note.id?{...n,question:e.target.value}:n)}))}/></label>
        <div className="citation-trace"><h3>Original evidence（要約とは別）</h3><blockquote>{source?.span||'原文の根拠は未指定です。'}</blockquote><p>{source?bibliography(source).text:'Source metadata 未指定'}</p><p>{source?.status||'Unverified'}</p></div><button className="secondary-button" onClick={()=>setDraft(d=>({...d,literature:d.literature.filter(n=>n.id!==note.id)}))}>文献メモを削除 {i+1}</button></fieldset>;})}<button className="secondary-button" disabled={draft.literature.length>=40} onClick={()=>setDraft(d=>({...d,literature:[...d.literature,{id:crypto.randomUUID(),evidenceId:'',summary:'',provenance:'Student',question:''}]}))}>文献メモを追加</button></section>}
    <section className="evidence-section" aria-labelledby="outline-heading"><h2 id="outline-heading">Editable Outline</h2><p className="muted">構成は自由です。Introduction・Evidence・Counterpointなど必要な節だけ追加してください。自動執筆はしません。</p>
      {draft.outline.map((section,i)=><fieldset className="evidence-entry" key={section.id}><legend>Section {i+1}</legend><label>節の見出し {i+1}<input aria-label={`節の見出し ${i+1}`} maxLength={20000} value={section.title} onChange={e=>setDraft(d=>({...d,outline:d.outline.map(s=>s.id===section.id?{...s,title:e.target.value}:s)}))}/></label><label>節のメモ {i+1}<textarea aria-label={`節のメモ ${i+1}`} rows={4} maxLength={20000} value={section.text} onChange={e=>setDraft(d=>({...d,outline:d.outline.map(s=>s.id===section.id?{...s,text:e.target.value}:s)}))}/></label>
        <div className="planning-actions"><button className="secondary-button" disabled={i===0} onClick={()=>setDraft(d=>{const outline=[...d.outline];[outline[i-1],outline[i]]=[outline[i],outline[i-1]];return {...d,outline};})}>節を上へ {i+1}</button><button className="secondary-button" onClick={()=>setDraft(d=>({...d,outline:d.outline.filter(s=>s.id!==section.id)}))}>節を削除 {i+1}</button></div></fieldset>)}<button className="secondary-button" disabled={draft.outline.length>=40} onClick={()=>setDraft(d=>({...d,outline:[...d.outline,{id:crypto.randomUUID(),title:'',text:''}]}))}>節を追加</button></section>
    <div className="draft-actions"><button className="primary-button" onClick={save}>このタブに保存</button><button className="secondary-button" onClick={copy}>入力メモをコピー</button><button className="secondary-button" onClick={clear}>Clear / この下書きを削除</button></div></fieldset><p className="draft-notice" role="status" aria-live="polite">{notice}</p><p className="muted">Report・Research・CitationはFoundation段階です。<Link href="/sources">Source Inspector ↗</Link></p></main>;
}
