"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {PLANNER_KEY,emptyPlanner,restorePlanner,validatePlanner,exportPlanner,deleteClass,attendanceSummary,todayView,civilAt} from '../lib/planner';
import type {Planner,ClassSlot,Assignment,Attendance} from '../lib/planner';
const days=['日','月','火','水','木','金','土'];
function useClock(){const [now,setNow]=useState<number|null>(null);useEffect(()=>{const update=()=>setNow(Date.now());update();const timer=setInterval(update,30000);window.addEventListener('focus',update);return()=>{clearInterval(timer);window.removeEventListener('focus',update);};},[]);return now;}
function useRecords(){
  const [data,setData]=useState<Planner>(emptyPlanner),[ready,setReady]=useState(false),[notice,setNotice]=useState('');
  useEffect(()=>{const load=()=>{try{const raw=localStorage.getItem(PLANNER_KEY);setData(raw?restorePlanner(JSON.parse(raw)):emptyPlanner(Intl.DateTimeFormat().resolvedOptions().timeZone));}catch{setNotice('保存データを読めません。自動上書きしません。Export済みデータを確認してください。');}setReady(true);};load();window.addEventListener('storage',load);window.addEventListener('unipilot-planner',load);return()=>{window.removeEventListener('storage',load);window.removeEventListener('unipilot-planner',load);};},[]);
  return {data,setData,ready,notice,setNotice};
}
function Today({data,now}:{data:Planner;now:number}){
  if(validatePlanner(data).length)return <p>入力修正後にTodayを表示します。</p>;
  const view=todayView(data,now);
  return <div className="today-grid"><section><h3>次の授業</h3><p>{view.next?`${civilAt(view.next.at,data.timezone).replace('T',' ')} · ${view.next.course.name}`:'登録された次の授業はありません。'}</p><p className="muted">{data.timezone} / 夏時間で曖昧・存在しない授業時刻は推測せずスキップします。</p></section>
    <section><h3>今日の課題</h3>{view.today.length?<ul>{view.today.map(a=><li key={a.id}>{a.title}</li>)}</ul>:<p>登録された今日の課題はありません。</p>}<h3>期限が近い課題・期限超過</h3>{view.tasks.length?<ul>{view.tasks.map(a=><li key={a.id}>{a.title} — {a.overdue?'期限超過':`残り${Math.ceil(a.remainingMs/3600000)}時間`} ({a.due.replace('T',' ')} {a.timezone})</li>)}</ul>:<p>登録された72時間以内の未完了課題はありません。</p>}</section>
    <section><h3>出席状況注意</h3>{view.warnings.length?<ul>{view.warnings.map(c=><li key={c.id}>{c.name}：あなたの欠席注意閾値に到達</li>)}</ul>:<p>設定した注意条件に該当する授業はありません。</p>}<h3>今やるなら</h3><p>{view.recommendation||'入力済みデータに候補はありません。'}</p><p className="muted">固定rule：期限超過→24h以内→72h以内→次の授業。期限順、同時刻はpriority順。大学の単位認定ルールではありません。</p></section></div>;
}
export function TodaysUniPilot(){const {data,ready,notice}=useRecords(),now=useClock();return <aside className="today-home writing-workspace" aria-label="Today's UniPilot"><p className="eyebrow">TODAY’S UNIPILOT / FOUNDATION</p><h2>入力した予定から、今日を整理。</h2><Link className="secondary-button" href="/planner">Plannerを開く ↗</Link>{notice&&<p role="status">{notice}</p>}{ready&&now!==null?<Today data={data} now={now}/>:<p>ローカルの予定を確認中…</p>}</aside>;}
const blankClass=():ClassSlot=>({id:'',name:'',day:1,start:'',end:'',location:'',instructor:''});
const blankTask=(timezone:string):Assignment=>({id:'',title:'',courseId:'',due:'',timezone,status:'not-started',priority:'normal',note:''});
export function PlannerWorkspace(){
  const {data,setData,ready,notice,setNotice}=useRecords(),now=useClock();const [tab,setTab]=useState('Today'),[course,setCourse]=useState<ClassSlot>(blankClass),[task,setTask]=useState<Assignment>(()=>blankTask('Asia/Tokyo')),[attendance,setAttendance]=useState<Attendance>({id:'',courseId:'',date:'',status:'present'}),[error,setError]=useState('');
  function accept(next:Planner){const errors=validatePlanner(next);if(errors.length){setError(errors.join(' '));return false;}setData(next);setError('');setNotice('未保存の変更があります。保存でHomeにも反映します。');return true;}
  function save(){try{localStorage.setItem(PLANNER_KEY,exportPlanner(data));window.dispatchEvent(new Event('unipilot-planner'));setNotice('このブラウザーへ保存しました。サーバー送信なし。');}catch(e){setError((e as Error).message);}}
  function clear(){if(!confirm('Plannerの授業・出席・課題をすべて削除しますか？'))return;try{localStorage.removeItem(PLANNER_KEY);window.dispatchEvent(new Event('unipilot-planner'));setCourse(blankClass());setTask(blankTask(data.timezone));setAttendance({id:'',courseId:'',date:'',status:'present'});setError('');setNotice('Plannerの保存・入力データを削除しました。');}catch{setError('ブラウザー保存を削除できません。サイトデータ設定を確認してください。');}}
  function download(){try{const url=URL.createObjectURL(new Blob([exportPlanner(data)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='unipilot-planner.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('ローカルJSONを作成しました。');}catch(e){setError((e as Error).message);}}
  return <main className="workspace writing-workspace calculator planner"><p className="eyebrow">09 / STUDENT PLANNER · LOCAL BETA</p><h1>予定を、自分の手で。</h1><p className="intro-copy">時間割・課題・出席を整理。入力していない予定は作りません。</p><p className="shell-notice">local-first / 日時と出席率はコード計算。大学公式の出席・単位認定制度ではありません。保存するまでHomeは更新されません。</p>
    <div className="journey-nav" aria-label="Planner sections">{['Today','Schedule','Assignments','Attendance'].map(t=><button className="secondary-button" key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div>
    <div id="planner-errors" role="alert">{error&&<p className="calc-error">{error}</p>}</div><p role="status" aria-live="polite">{notice}</p>
    <fieldset className="writing-controls" disabled={!ready}><legend className="sr-only">Planner editor</legend><label>表示・授業timezone<input aria-label="表示・授業timezone" aria-describedby="planner-errors" value={data.timezone} onChange={e=>setData(d=>({...d,timezone:e.target.value}))}/></label><p className="muted">IANA名（例 Asia/Tokyo）。課題の期限timezoneは課題ごとに保持し、表示timezoneを変えても期限の瞬間は変えません。</p>
    {tab==='Today'&&now!==null&&<Today data={data} now={now}/>}
    {tab==='Schedule'&&<section className="evidence-section"><h2>Schedule</h2><form onSubmit={e=>{e.preventDefault();const c={...course,id:course.id||crypto.randomUUID()};if(accept({...data,classes:[...data.classes.filter(x=>x.id!==c.id),c]}))setCourse(blankClass());}}>
      <div className="evidence-fields"><label>授業名<input aria-label="授業名" maxLength={200} value={course.name} onChange={e=>setCourse(c=>({...c,name:e.target.value}))}/></label><label>曜日<select aria-label="曜日" value={course.day} onChange={e=>setCourse(c=>({...c,day:Number(e.target.value)}))}>{days.map((d,i)=><option value={i} key={d}>{d}</option>)}</select></label><label>開始時刻<input aria-label="開始時刻" aria-describedby="planner-errors" type="time" value={course.start} onChange={e=>setCourse(c=>({...c,start:e.target.value}))}/></label><label>終了時刻<input aria-label="終了時刻" aria-describedby="planner-errors" type="time" value={course.end} onChange={e=>setCourse(c=>({...c,end:e.target.value}))}/></label><label>教室（任意）<input value={course.location} maxLength={200} onChange={e=>setCourse(c=>({...c,location:e.target.value}))}/></label><label>担当者（任意）<input value={course.instructor} maxLength={200} onChange={e=>setCourse(c=>({...c,instructor:e.target.value}))}/></label></div><button className="primary-button">{course.id?'授業を更新':'授業を追加'}</button><button type="button" className="secondary-button" onClick={()=>setCourse(blankClass())}>入力をリセット</button></form>
      <div className="calc-table"><table><caption>登録時間割</caption><thead><tr><th scope="col">授業</th><th scope="col">時間・場所</th><th scope="col">操作</th></tr></thead><tbody>{data.classes.map(c=><tr key={c.id}><th scope="row">{c.name}</th><td>{days[c.day]} {c.start}–{c.end}<br/>{c.location} {c.instructor}</td><td><button className="secondary-button" aria-label={`${c.name}を編集`} onClick={()=>setCourse(c)}>編集</button><button className="secondary-button" aria-label={`${c.name}を削除`} onClick={()=>{if(confirm('授業と関連出席を削除しますか？課題は授業紐付けのみ解除します。'))accept(deleteClass(data,c.id));}}>削除</button></td></tr>)}</tbody></table></div></section>}
    {tab==='Assignments'&&<section className="evidence-section"><h2>Assignments</h2><form onSubmit={e=>{e.preventDefault();const a={...task,id:task.id||crypto.randomUUID()};if(accept({...data,assignments:[...data.assignments.filter(x=>x.id!==a.id),a]}))setTask(blankTask(data.timezone));}}><div className="evidence-fields"><label>課題名<input aria-label="課題名" maxLength={200} value={task.title} onChange={e=>setTask(t=>({...t,title:e.target.value}))}/></label><label>関連授業<select aria-label="関連授業" value={task.courseId} onChange={e=>setTask(t=>({...t,courseId:e.target.value}))}><option value="">未指定</option>{data.classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>期限<input aria-label="期限" type="datetime-local" aria-describedby="planner-errors" value={task.due} onChange={e=>setTask(t=>({...t,due:e.target.value}))}/></label><label>期限timezone<input aria-label="期限timezone" aria-describedby="planner-errors" value={task.timezone} onChange={e=>setTask(t=>({...t,timezone:e.target.value}))}/></label><label>課題状態<select aria-label="課題状態" value={task.status} onChange={e=>setTask(t=>({...t,status:e.target.value as Assignment['status']}))}><option value="not-started">Not started</option><option value="in-progress">In progress</option><option value="done">Done</option></select></label><label>Priority<select aria-label="Priority" value={task.priority} onChange={e=>setTask(t=>({...t,priority:e.target.value as Assignment['priority']}))}><option value="normal">Normal</option><option value="high">High</option><option value="low">Low</option></select></label></div><label>課題メモ<textarea maxLength={2000} value={task.note} onChange={e=>setTask(t=>({...t,note:e.target.value}))}/></label><button className="primary-button">{task.id?'課題を更新':'課題を追加'}</button><button type="button" className="secondary-button" onClick={()=>setTask(blankTask(data.timezone))}>課題入力をリセット</button></form>
    <ul className="planner-list">{data.assignments.map(a=><li key={a.id}><strong>{a.title}</strong><p>{a.due.replace('T',' ')} {a.timezone} · {a.status}</p><button className="secondary-button" aria-label={`${a.title}を編集`} onClick={()=>setTask(a)}>編集</button><button className="secondary-button" aria-label={`${a.title}を削除`} onClick={()=>{if(confirm('この課題を削除しますか？'))accept({...data,assignments:data.assignments.filter(x=>x.id!==a.id)});}}>削除</button></li>)}</ul></section>}
    {tab==='Attendance'&&<section className="evidence-section"><h2>Attendance</h2><label>欠席注意閾値（任意・回数）<input aria-label="欠席注意閾値" aria-describedby="planner-errors" type="number" min="1" max="1000" value={data.absenceThreshold??''} onChange={e=>setData(d=>({...d,absenceThreshold:e.target.value===''?null:Number(e.target.value)}))}/></label><p className="muted">大学の規則ではなく、あなたの注意設定。率＝present÷(present+late+absent)。excusedは分母から除外、lateはpresentとして数えません。記録0は未定義。</p><form onSubmit={e=>{e.preventDefault();const a={...attendance,id:attendance.id||crypto.randomUUID()};if(accept({...data,attendance:[...data.attendance.filter(x=>x.id!==a.id),a]}))setAttendance({...attendance,id:'',date:''});}}><div className="evidence-fields"><label>出席の授業<select aria-label="出席の授業" value={attendance.courseId} onChange={e=>setAttendance(a=>({...a,courseId:e.target.value}))}><option value="">選択してください</option>{data.classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>記録日<input aria-label="記録日" type="date" aria-describedby="planner-errors" value={attendance.date} onChange={e=>setAttendance(a=>({...a,date:e.target.value}))}/></label><label>出席状態<select aria-label="出席状態" value={attendance.status} onChange={e=>setAttendance(a=>({...a,status:e.target.value as Attendance['status']}))}>{['present','late','absent','excused'].map(s=><option key={s}>{s}</option>)}</select></label></div><button className="primary-button">{attendance.id?'出席を更新':'出席を記録'}</button></form>
      <ul className="planner-list">{data.classes.map(c=>{const s=attendanceSummary(data,c.id);return <li key={c.id}>{c.name}: present {s.present} / late {s.late} / absent {s.absent} / excused {s.excused} · 率 {s.percentage===null?'—':s.percentage.toFixed(1)+'%'} {s.warning?'注意（独自閾値）':''}</li>;})}</ul><ul className="planner-list">{data.attendance.map(a=><li key={a.id}>{data.classes.find(c=>c.id===a.courseId)?.name} {a.date} {a.status}<button className="secondary-button" aria-label={`${a.date}の出席を編集`} onClick={()=>setAttendance(a)}>編集</button><button className="secondary-button" aria-label={`${a.date}の出席を削除`} onClick={()=>{if(confirm('この出席記録を削除しますか？'))accept({...data,attendance:data.attendance.filter(x=>x.id!==a.id)});}}>削除</button></li>)}</ul></section>}
    <div className="draft-actions"><button className="primary-button" onClick={save}>Plannerを保存</button><button className="secondary-button" onClick={download}>Export Planner</button><button className="secondary-button" onClick={clear}>Clear all Planner</button></div><label>Import Planner JSON<input aria-label="Import Planner JSON" type="file" accept="application/json,.json" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;try{if(f.size>2000000)throw Error('Importは2MB以内です。');const next=restorePlanner(JSON.parse(await f.text()));if(confirm('現在の未保存Planner入力をImport内容で置き換えますか？保存まではブラウザー保存を変更しません。'))accept(next);}catch(err){setError((err as Error).message);}}}/></label></fieldset></main>;
}
