"use client";
import {useState} from 'react';
import {emptyEmail,PURPOSES,templateEmail} from '../lib/professorEmail';
import type {EmailInput} from '../lib/professorEmail';
export function ProfessorEmailWorkspace(){
  const [input,setInput]=useState<EmailInput>(emptyEmail),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[generated,setGenerated]=useState(false),[stale,setStale]=useState(false);
  function change(k:keyof EmailInput,v:string){setInput(d=>({...d,[k]:v}));if(generated)setStale(true);}
  function generate(){try{if(generated&&!confirm('編集済みの件名・本文を、現在の入力から作るTemplate draftで置き換えますか？'))return;const r=templateEmail(input);setSubject(r.subject);setBody(r.body);setGenerated(true);setStale(false);setError('');setNotice(`${r.label}。未入力項目 ${r.missing.length}件。${r.warning}`);}catch(e){setError((e as Error).message);}}
  async function copy(){try{await navigator.clipboard.writeText(`件名：${subject}\n\n${body}`);setNotice('編集済みpreviewをコピーしました。メールは送信していません。');}catch{setNotice('コピーできません。件名・本文を選択して手動コピーしてください。');}}
  return <main className="workspace writing-workspace calculator"><p className="eyebrow">10 / PROFESSOR EMAIL · TEMPLATE BETA</p><h1>伝えたい事実を、丁寧に。</h1><p className="intro-copy">入力 → Template draft → 自分で編集・確認 → Copy。</p><p className="shell-notice">Template draft専用。AI生成ではありません。API停止時にも利用できるローカル機能です。外部AI・mail API・自動送信・サーバー保存はOFF。</p>
    <div id="email-errors" role="alert">{error&&<p className="calc-error">{error}</p>}</div><section className="evidence-section"><h2>入力した事実</h2><div className="evidence-fields"><label>宛名（任意）<input aria-label="宛名" maxLength={300} value={input.recipient} onChange={e=>change('recipient',e.target.value)}/></label><label>宛先の役割<input aria-label="宛先の役割" maxLength={300} value={input.role} onChange={e=>change('role',e.target.value)}/></label><label>授業名<input aria-label="メールの授業名" maxLength={300} value={input.course} onChange={e=>change('course',e.target.value)}/></label><label>用途<select aria-label="用途" value={input.purpose} onChange={e=>change('purpose',e.target.value)}>{PURPOSES.map(p=><option key={p}>{p}</option>)}</select></label><label>Tone<select aria-label="Tone" value={input.tone} onChange={e=>change('tone',e.target.value)}>{['丁寧','簡潔','相談的'].map(t=><option key={t}>{t}</option>)}</select></label></div>
      <label>事実・日時（入力した内容のみ使用）<textarea aria-label="事実・日時" aria-describedby="email-errors" maxLength={2000} value={input.facts} onChange={e=>change('facts',e.target.value)}/></label><label>依頼したいこと<textarea aria-label="依頼したいこと" maxLength={500} value={input.action} onChange={e=>change('action',e.target.value)}/></label><p className="muted">日付・理由・提出期限・診断書・大学規則・約束を未入力のまま推測しません。空欄は未入力として残ります。</p><button className="primary-button" onClick={generate}>Template draftを作成</button></section>
    {generated&&<section className="evidence-section email-preview"><h2>件名・本文 preview（編集可能）</h2>{stale&&<p role="status" className="calc-error">入力が変わりました。現在のpreviewは古い入力に基づきます。再作成するまでCopyは無効です。</p>}<label>件名<input aria-label="件名" maxLength={1000} value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>本文<textarea aria-label="本文" maxLength={10000} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="primary-button" disabled={stale||!subject.trim()||!body.trim()} onClick={copy}>編集済みpreviewをCopy</button><p className="muted">プレースホルダーを含む可能性があります。宛先・氏名・事実・依頼・約束を確認してください。Copyは送信ではありません。</p></section>}
    <button className="secondary-button" onClick={()=>{if(confirm('メールの入力・previewを消去しますか？')){setInput(emptyEmail());setSubject('');setBody('');setGenerated(false);setStale(false);setError('');setNotice('メール入力・previewを消去しました。');}}}>Clear Email</button><p role="status" aria-live="polite">{notice}</p></main>;
}
