"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {PLAN_KEY,emptyPlanInput,schedule,reschedule,restoreStudyPlan,exportStudyPlan,nextStudyBlock} from '../lib/studyPlan';
import type {PlanInput,StudyPlan,Topic} from '../lib/studyPlan';
import {MEMORY_KEY,restoreMemory} from '../lib/learningMemory';
import {PLANNER_KEY,restorePlanner,civilAt,zonedEpoch} from '../lib/planner';
function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function blankTopic():Topic{return {id:'',subject:'',topic:'',minutes:60,priority:2,confidence:3,deadline:'',source:'manual',sourceId:'',context:''};}
export function NextStudy(){const [block,setBlock]=useState<ReturnType<typeof nextStudyBlock>>(null),[error,setError]=useState('');useEffect(()=>{const load=()=>{try{const raw=localStorage.getItem(PLAN_KEY);setBlock(raw?nextStudyBlock(restoreStudyPlan(JSON.parse(raw)),localDate()):null);setError('');}catch{setBlock(null);setError('保存済みStudy Planを確認してください。');}};load();window.addEventListener('storage',load);window.addEventListener('unipilot-plan',load);const timer=setInterval(load,30000);return()=>{window.removeEventListener('storage',load);window.removeEventListener('unipilot-plan',load);clearInterval(timer);};},[]);return <section aria-label="次の学習"><h3>次の学習</h3><p>{error||(block?`${block.date} · ${block.subject} / ${block.topic} · ${block.duration}分`:'今日以降の保存済み学習planはありません。')}</p><Link href="/plan" className="secondary-button">Study Planを開く</Link></section>;}
export function StudyPlanWorkspace(){
  const [input,setInput]=useState<PlanInput>(emptyPlanInput),[draft,setDraft]=useState<Topic>(blankTopic),[plan,setPlan]=useState<StudyPlan|null>(null),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[memoryOpt,setMemoryOpt]=useState(false),[plannerOpt,setPlannerOpt]=useState(false),[choices,setChoices]=useState<Topic[]>([]),[from,setFrom]=useState('');
  useEffect(()=>{try{const raw=localStorage.getItem(PLAN_KEY);if(raw){const saved=restoreStudyPlan(JSON.parse(raw));setPlan(saved);setInput(saved.input);setMemoryOpt(saved.input.topics.some(t=>t.source==='memory'));setPlannerOpt(saved.input.topics.some(t=>t.source==='planner'));}else setInput(p=>({...p,start:localDate()}));}catch{setError('保存済みPlanを読み込めません。自動上書きはしません。');}setFrom(localDate());setReady(true);},[]);
  function change(p:PlanInput){setInput(p);setPlan(null);setNotice('入力が変更されました。計画を生成してから保存してください。');}
  function opt(source:'memory'|'planner',enabled:boolean){if(source==='memory')setMemoryOpt(enabled);else setPlannerOpt(enabled);setChoices(c=>c.filter(t=>t.source!==source));if(!enabled){change({...input,topics:input.topics.filter(t=>t.source!==source)});return;}try{
    let added:Topic[]=[];
    if(source==='memory'){const m=restoreMemory(JSON.parse(localStorage.getItem(MEMORY_KEY)||'{"schema":"unipilot-learning-memory-v1","items":[]}'));added=m.items.map(m=>({id:'memory:'+m.id,subject:m.subject,topic:m.topic,minutes:60,priority:m.weakPoints&&m.weaknessConfirmed?3:2,confidence:m.confidence,deadline:'',source:'memory',sourceId:m.id,context:`本人確認の弱点: ${m.weakPoints} / 間違い: ${m.mistakes} / 学習日: ${m.lastStudied}`}));}
    else {const raw=localStorage.getItem(PLANNER_KEY);if(raw){const p=restorePlanner(JSON.parse(raw)),zone=Intl.DateTimeFormat().resolvedOptions().timeZone;added=[...p.assignments.filter(a=>a.status!=='done').map(a=>({id:'assignment:'+a.id,subject:p.classes.find(c=>c.id===a.courseId)?.name||'登録課題',topic:a.title,minutes:60,priority:a.priority==='high'?3:a.priority==='low'?1:2,confidence:3,deadline:civilAt(zonedEpoch(a.due,a.timezone),zone).slice(0,10),source:'planner' as const,sourceId:a.id,context:`登録期限 ${a.due} ${a.timezone}。学習ブロックは日単位。締切日の時刻前に実行する必要があります。`})),...p.classes.map(c=>({id:'class:'+c.id,subject:c.name,topic:'授業の復習',minutes:60,priority:2,confidence:3,deadline:'',source:'planner' as const,sourceId:c.id,context:`登録授業: ${['日','月','火','水','木','金','土'][c.day]} ${c.start}–${c.end} ${p.timezone}`}))];}}
    setChoices(c=>[...c.filter(t=>t.source!==source),...added]);setNotice('候補を選択し、必要時間・自己評価を確認してから追加してください。初期60分は見積もり用で、実測負荷ではありません。');setError('');
  }catch(e){setError((e as Error).message);}}
  function generate(){try{if(input.start<localDate())throw Error('開始日は今日以降にしてください。');const next=schedule(input);setPlan(next);setError('');setNotice('日単位の計画を生成しました。まだ保存されていません。');}catch(e){setError((e as Error).message);}}
  function save(){if(!plan)return;try{localStorage.setItem(PLAN_KEY,exportStudyPlan(plan));window.dispatchEvent(new Event('unipilot-plan'));setNotice('Planをこのブラウザーへ保存しました。Todayに反映されます。');setError('');}catch(e){setError((e as Error).message);}}
  function clear(){if(!confirm('Study Planと入力・取り込みコピーをすべて削除しますか？'))return;try{localStorage.removeItem(PLAN_KEY);window.dispatchEvent(new Event('unipilot-plan'));setInput({...emptyPlanInput(),start:localDate()});setPlan(null);setDraft(blankTopic());setChoices([]);setMemoryOpt(false);setPlannerOpt(false);setError('');setNotice('Planと入力を削除しました。');}catch{setError('削除できません。ブラウザーのサイトデータ設定を確認してください。');}}
  const edit=(key:keyof Topic,v:string|number)=>setDraft(t=>({...t,[key]:v}));
  return <main className="workspace writing-workspace planner"><p className="eyebrow">12 / AI STUDY PLAN · LOCAL BETA</p><h1>使える時間から、学びを計画。</h1><p className="intro-copy">目標と必要時間を入力すると、期限・優先度に沿って配分します。</p><p className="shell-notice">Local only / 計算による計画です。AI接続なしでも動作します。AIによる個別最適化は未検証です。保存した目標・topic・自己評価・取り込みメモ・blockだけがこのブラウザーに残ります。</p><p>日単位の配分（1block最大30分）。1日の時間は授業・睡眠などを除いた学習可能時間を入力してください。今日は残りの時間で見積もってください。時刻の衝突確認は行いません。</p><p id="plan-errors" role="alert">{error}</p><p role="status" aria-live="polite">{notice}</p>
    <fieldset className="writing-controls" disabled={!ready}><legend>計画の条件</legend><label>学習目標<input maxLength={2000} aria-describedby="plan-errors" value={input.goal} onChange={e=>change({...input,goal:e.target.value})}/></label><div className="evidence-fields"><label>開始日<input type="date" aria-describedby="plan-errors" value={input.start} onChange={e=>change({...input,start:e.target.value})}/></label><label>目標日<input type="date" aria-describedby="plan-errors" value={input.target} onChange={e=>change({...input,target:e.target.value})}/></label><label>1日の学習可能時間（分）<input type="number" min={0} max={720} aria-describedby="plan-errors" value={input.minutesPerDay} onChange={e=>change({...input,minutesPerDay:Number(e.target.value)})}/></label></div><fieldset><legend>学習できる曜日</legend><div className="weekday-options">{['日','月','火','水','木','金','土'].map((d,i)=><label className="consent-row" key={d}><input type="checkbox" checked={input.weekdays.includes(i)} onChange={e=>change({...input,weekdays:e.target.checked?[...input.weekdays,i]:input.weekdays.filter(v=>v!==i)})}/>{d}</label>)}</div></fieldset>
    <section className="evidence-section"><h2>取り込み（任意）</h2><label className="consent-row"><input type="checkbox" checked={memoryOpt} onChange={e=>opt('memory',e.target.checked)}/>Learning Memoryの候補を使う</label><label className="consent-row"><input type="checkbox" checked={plannerOpt} onChange={e=>opt('planner',e.target.checked)}/>Plannerの候補を使う</label><p>選んだ情報は保存時にPlanへコピーされます。元データの削除はコピーへ自動反映されません。許可を外して再保存すると、このPlanの取り込み情報を除去できます。</p><ul className="planner-list">{choices.map(t=><li key={t.id}>{t.subject} / {t.topic}<button className="secondary-button" aria-label={`${t.topic}を候補から選ぶ`} onClick={()=>setDraft({...t})}>選んで確認</button></li>)}</ul></section>
    <section className="evidence-section"><h2>Topicと見積もり</h2><div className="evidence-fields">{([['subject','科目'],['topic','Topic']] as const).map(([k,l])=><label key={k}>{l}<input maxLength={200} aria-describedby="plan-errors" value={draft[k]} onChange={e=>edit(k,e.target.value)}/></label>)}<label>必要時間（分）<input type="number" min={1} max={10080} aria-describedby="plan-errors" value={draft.minutes} onChange={e=>edit('minutes',Number(e.target.value))}/></label><label>優先度<select aria-label="優先度" value={draft.priority} onChange={e=>edit('priority',Number(e.target.value))}>{[3,2,1].map(n=><option key={n} value={n}>{n} {n===3?'高':n===2?'中':'低'}</option>)}</select></label><label>現在の自己評価<select aria-label="現在の自己評価" value={draft.confidence} onChange={e=>edit('confidence',Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}/5</option>)}</select></label><label>Topic期限（任意）<input type="date" aria-describedby="plan-errors" value={draft.deadline} onChange={e=>edit('deadline',e.target.value)}/></label></div><p>{draft.context}</p><button className="secondary-button" onClick={()=>{if(!draft.subject.trim()||!draft.topic.trim()){setError('科目とtopicを入力してください。');return;}if((draft.source==='memory'&&!memoryOpt)||(draft.source==='planner'&&!plannerOpt)){setError('取り込み元の許可を確認してください。');return;}const t={...draft,id:draft.id||crypto.randomUUID()};change({...input,topics:[...input.topics.filter(x=>x.id!==t.id),t]});setDraft(blankTopic());setError('');}}>Topicを追加・更新</button><button className="secondary-button" onClick={()=>setDraft(blankTopic())}>Topic入力をリセット</button><ul className="planner-list">{input.topics.map(t=><li key={t.id}>{t.subject} / {t.topic} — {t.minutes}分 / 優先度{t.priority} / 自己評価{t.confidence} / {t.source}<button className="secondary-button" aria-label={`${t.topic}を編集`} onClick={()=>setDraft({...t})}>編集</button><button className="secondary-button" aria-label={`${t.topic}を削除`} onClick={()=>change({...input,topics:input.topics.filter(x=>x.id!==t.id)})}>削除</button></li>)}</ul></section><button className="primary-button" onClick={generate}>計画を生成</button></fieldset>
    {plan&&<section className="evidence-section"><h2>Study blocks</h2><p role="status">{plan.overCapacity?`Over capacity — ${plan.remaining.reduce((s,r)=>s+r.minutes,0)}分が期限までに入りません。時間・期限・見積もりを見直してください。`:'Capacity OK — 入力した学習可能時間内です。'}</p><ul className="planner-list">{plan.blocks.map((b,i)=><li key={b.id}><strong>{b.date} · {b.subject} / {b.topic} · {b.duration}分</strong><p>{b.reason}</p><label>状態 {i+1} · {b.date} {b.topic}<select value={b.status} onChange={e=>{setPlan({...plan,blocks:plan.blocks.map(x=>x.id===b.id?{...x,status:e.target.value as typeof x.status}:x)});setNotice('状態は未保存です。');}}>{['Planned','Done','Skipped'].map(s=><option key={s}>{s}</option>)}</select></label></li>)}</ul><label>再配置の開始日<input type="date" aria-describedby="plan-errors" value={from} onChange={e=>setFrom(e.target.value)}/></label><button className="secondary-button" onClick={()=>{try{if(from<localDate())throw Error('今日以降を指定してください。');const next=reschedule(plan,from);setPlan(next);setInput(next.input);setError('');setNotice('Doneを保持し、Skippedと未完了の時間を再配置しました。保存で反映されます。');}catch(e){setError((e as Error).message);}}}>未完了を再配置</button></section>}
    <div className="draft-actions"><button className="primary-button" disabled={!plan} onClick={save}>Study Planを保存</button><button className="secondary-button" disabled={!plan} onClick={()=>{if(!plan)return;const url=URL.createObjectURL(new Blob([exportStudyPlan(plan)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='unipilot-study-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Export Study Plan</button><button className="secondary-button" onClick={clear}>Clear all Study Plan</button></div>
  </main>;
}
