// Local Demo only; no health/chat/model request reaches an external service.
const {chromium}=require(process.env.UNIPILOT_PLAYWRIGHT_MODULE||'playwright');
const {expect}=require((process.env.UNIPILOT_PLAYWRIGHT_MODULE||'playwright')+'/test');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const base=process.env.UNIPILOT_QA_URL||'http://127.0.0.1:3049',out=path.resolve(__dirname,process.env.UNIPILOT_QA_OUTPUT||'../qa/phase53');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();const errors=[],posts=[],layouts=[];page.on('pageerror',e=>errors.push(e.message));
 await context.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(req.method()==='POST')posts.push(url.pathname);if(url.pathname==='/health')return route.fulfill({status:200,headers:{'content-type':'application/json','access-control-allow-origin':'*'},body:'{"status":"ok","loaded":true}'});if(url.origin!==new URL(base).origin)return route.abort();return route.continue();});
 await page.goto(base+'/gpa');await page.getByRole('button',{name:'科目を追加',exact:true}).click();await page.getByLabel('科目名 1',{exact:true}).fill('Demo: 科目A');await page.getByLabel('単位 1',{exact:true}).fill('3');await page.getByRole('button',{name:'科目を追加',exact:true}).click();await page.getByLabel('科目名 2',{exact:true}).fill('Demo: 科目B');await page.getByLabel('単位 2',{exact:true}).fill('1');await page.getByLabel('成績 2',{exact:true}).selectOption('c');await expect(page.getByTestId('current-gpa')).toHaveText('3.500');
 await page.getByLabel('What-if 成績 2',{exact:true}).selectOption('a');await expect(page.getByTestId('whatif-gpa')).toHaveText('4.000');await expect(page.getByLabel('成績 2',{exact:true})).toHaveValue('c');await page.getByLabel('What-if 成績 2',{exact:true}).selectOption('');
 await page.getByLabel('目標GPA',{exact:true}).fill('4');await page.getByLabel('今後のGPA算入単位',{exact:true}).fill('1');await page.getByText('Impossible under current policy',{exact:true}).waitFor();await expect(page.getByTestId('required-average')).toHaveText('6.000');
 await page.getByLabel('Policy rounding',{exact:true}).selectOption('floor');await page.getByRole('button',{name:'GPAをこのタブに保存',exact:true}).click();await page.reload();await expect(page.getByTestId('current-gpa')).toHaveText('3.500');await expect(page.getByLabel('What-if 成績 2',{exact:true})).toHaveValue('');
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'JSON export',exact:true}).click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'unipilot-gpa.json');const stream=await download.createReadStream();let text='';for await(const chunk of stream)text+=chunk;const exported=JSON.parse(text);assert.equal(exported.current.rawGpa,3.5);assert.equal(exported.draft.courses[0].name,'Demo: 科目A');
 await page.getByRole('checkbox',{name:'科目 2 を算入',exact:true}).uncheck();await expect(page.getByTestId('current-gpa')).toHaveText('4.000');await page.getByRole('checkbox',{name:'科目 2 を算入',exact:true}).check();
 await page.getByLabel('再履修元 2',{exact:true}).selectOption({label:'Demo: 科目A'});await page.getByLabel('再履修方針',{exact:true}).selectOption('replace');await page.getByText(/Replace old gradeは同じ単位数/).waitFor();assert.equal(await page.getByTestId('current-gpa').count(),0);await page.getByLabel('再履修方針',{exact:true}).selectOption('exclude-old');await expect(page.getByTestId('current-gpa')).toHaveText('2.000');await page.getByLabel('再履修方針',{exact:true}).selectOption('both');await expect(page.getByTestId('current-gpa')).toHaveText('3.500');
 await page.getByLabel('単位 1',{exact:true}).fill('-1');await page.locator('#gpa-errors .calc-error').first().waitFor();assert.equal(await page.getByTestId('current-gpa').count(),0);assert.equal(await page.getByLabel('単位 1',{exact:true}).getAttribute('aria-describedby'),'gpa-errors');await page.getByLabel('単位 1',{exact:true}).fill('3');
 for(const width of [360,390,768,1024,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth));layouts.push({route:'/gpa',width,overflow:false});if(width===390||width===1440){await page.locator('#gpa-result').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,`gpa-result-${width}.png`)});}}
 await page.setViewportSize({width:360,height:900});const targets=await page.locator('main button,main select,main input:not([type=checkbox])').evaluateAll(nodes=>nodes.map(n=>({w:n.getBoundingClientRect().width,h:n.getBoundingClientRect().height})));assert.ok(targets.every(r=>r.w>=44&&r.h>=44));await page.getByLabel('単位 1',{exact:true}).focus();await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle),'solid');await page.emulateMedia({reducedMotion:'reduce'});
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Clear GPA',exact:true}).click();await page.reload();assert.equal(await page.getByLabel('科目名 1',{exact:true}).count(),0);await expect(page.getByTestId('current-gpa')).toHaveText('—');assert.equal(await page.evaluate(()=>sessionStorage.getItem('unipilot-gpa-v1')),null);
 await page.goto(base+'/degree');await page.getByRole('button',{name:'単位科目を追加',exact:true}).click();await page.getByLabel('単位科目名 1',{exact:true}).fill('Demo: 架空科目');await page.getByLabel('取得単位 1',{exact:true}).fill('2.5');await expect(page.getByTestId('degree-total')).toHaveText('2.5');assert.match(await page.locator('#degree-status').innerText(),/FIXTURE_ONLY/);assert.ok(await page.getByRole('cell',{name:'9.5',exact:true}).count());
 await page.getByLabel('規則のデモ状態',{exact:true}).selectOption('unknown');assert.match(await page.locator('#degree-status').innerText(),/UNKNOWN/);assert.equal(await page.getByRole('table').count(),1);await page.getByLabel('規則のデモ状態',{exact:true}).selectOption('conflict');assert.match(await page.locator('#degree-status').innerText(),/VERSION_CONFLICT/);await page.getByLabel('規則のデモ状態',{exact:true}).selectOption('fixture');
 for(const width of [360,390,768,1024,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth));layouts.push({route:'/degree',width,overflow:false});if(width===390||width===1440){await page.locator('#degree-status').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,`degree-result-${width}.png`)});}}
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Clear credits',exact:true}).click();await expect(page.getByTestId('degree-total')).toHaveText('0');assert.deepEqual(posts,[]);assert.deepEqual(errors,[]);
 fs.writeFileSync(path.join(out,'calculator-results.json'),JSON.stringify({DEMO:'PASS',fixtureOnly:true,layouts,weightedGpa:true,whatIf:true,targetImpossible:true,retakeModes:true,rounding:true,exclude:true,invalidInput:true,errorAssociation:true,sessionSaveReload:true,clear:true,jsonExport:true,degreeCategories:true,degreeMissingSource:true,degreeVersionConflict:true,targets44:true,keyboardFocus:true,reducedMotion:true,noPost:true,pageErrors:errors},null,2)+'\n');await browser.close();console.log('PASS: GPA/Degree interactions and10 populated width checks');
})().catch(e=>{console.error(e);process.exit(1);});
