// Isolated local browser fixtures; no student records, external model or production calls.
const {chromium}=require(process.env.UNIPILOT_PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const base=process.env.UNIPILOT_QA_URL||'http://127.0.0.1:3054',out=path.resolve(__dirname,'../qa/phase54');
(async()=>{
 fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Tokyo'}),page=await context.newPage();const errors=[],posts=[],layouts=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await context.route('**/*',route=>{const r=route.request(),u=new URL(r.url());if(r.method()==='POST')posts.push(u.pathname);if(u.pathname==='/health')return route.fulfill({status:200,headers:{'content-type':'application/json','access-control-allow-origin':'*'},body:'{"status":"ok","loaded":true}'});if(u.origin!==new URL(base).origin)return route.abort();return route.continue();});
 await page.clock.install({time:new Date('2026-09-14T09:00:00Z')});
 const button=n=>page.getByRole('button',{name:n,exact:true}),label=n=>page.getByLabel(n,{exact:true});
 const saved=key=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
 async function widths(route){for(const width of [360,390,768,1024,1440]){await page.setViewportSize({width,height:950});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),`${route}/${width} overflow`);layouts.push({route,width,overflow:false});if(width===390||width===1440)await page.screenshot({path:path.join(out,`${route}-${width}.png`)});}}
 await page.goto(base+'/memory');await label('科目').fill('Demo数学');await label('Topic').fill('積分');await label('最後に学習した日').fill('2026-09-13');await label('確認した弱点').fill('置換の選択');assert.equal(await saved('unipilot-learning-memory-v1'),null);await button('Save to learning memory').click();assert.match(await page.locator('#memory-errors').innerText(),/本人/);assert.equal(await saved('unipilot-learning-memory-v1'),null);
 await label('弱点の内容を自分で確認しました').check();await label('情報源').selectOption('quiz result');await label('出典・結果のメモ').fill('Demo練習2問目');await label('自分のConfidence').selectOption('2');await button('Save to learning memory').click();let memory=await saved('unipilot-learning-memory-v1');assert.equal(memory.items[0].confidence,2);assert.equal(memory.items[0].sourceType,'quiz result');await page.reload();await page.waitForFunction(()=>document.querySelector('main fieldset')?.disabled===false);await button('積分を編集').click();await label('学生メモ').fill('例題を復習');assert.equal((await saved('unipilot-learning-memory-v1')).items[0].note,'');await button('Save to learning memory').click();assert.equal((await saved('unipilot-learning-memory-v1')).items[0].note,'例題を復習');
 const memoryDownload=page.waitForEvent('download');await button('Export learning memory').click();assert.equal(JSON.parse(fs.readFileSync(await (await memoryDownload).path(),'utf8')).items.length,1);await widths('memory');
 await page.goto(base+'/plan');assert.equal(await label('Learning Memoryの候補を使う').isChecked(),false);assert.equal(await label('Plannerの候補を使う').isChecked(),false);await label('学習目標').fill('Demo復習');await label('目標日').fill('2026-09-15');await label('Learning Memoryの候補を使う').check();await button('積分を候補から選ぶ').click();assert.equal(await label('現在の自己評価').inputValue(),'2');await label('必要時間（分）').fill('150');await button('Topicを追加・更新').click();await button('計画を生成').click();assert.ok(await page.getByText(/Over capacity — 30分/).isVisible());assert.equal(await saved('unipilot-study-plan-v1'),null);await button('Study Planを保存').click();let plan=await saved('unipilot-study-plan-v1');assert.equal(plan.blocks.reduce((s,b)=>s+b.duration,0),120);assert.equal(plan.input.topics[0].source,'memory');
 await page.getByRole('combobox',{name:/^状態 2/}).selectOption('Done');await label('再配置の開始日').fill('2026-09-14');await button('未完了を再配置').click();await button('Study Planを保存').click();plan=await saved('unipilot-study-plan-v1');assert.equal(plan.blocks.filter(b=>b.status==='Done').length,1);assert.equal(new Set(plan.blocks.map(b=>b.id)).size,plan.blocks.length);
 await page.goto(base+'/');await page.getByLabel('次の学習',{exact:true}).getByText(/積分/).waitFor();assert.match(await page.getByLabel('次の学習',{exact:true}).innerText(),/積分/);await page.goto(base+'/plan');await widths('plan');
 await label('Learning Memoryの候補を使う').uncheck();assert.equal(await button('Study Planを保存').isEnabled(),false);await button('計画を生成').click();assert.match(await page.locator('#plan-errors').innerText(),/Topic/);
 // Planner candidates only after opt-in; show and select existing data.
 await page.evaluate(()=>localStorage.setItem('unipilot-planner-v1',JSON.stringify({schema:'unipilot-planner-v1',timezone:'Asia/Tokyo',classes:[],attendance:[],absenceThreshold:null,assignments:[{id:'demo',title:'Demo提出',courseId:'',due:'2026-09-15T12:00',timezone:'Asia/Tokyo',status:'not-started',priority:'high',note:''}]})));
 await label('Plannerの候補を使う').check();await button('Demo提出を候補から選ぶ').click();await button('Topicを追加・更新').click();await label('1日の学習可能時間（分）').fill('0');await button('計画を生成').click();await button('Study Planを保存').click();plan=await saved('unipilot-study-plan-v1');assert.equal(plan.blocks.length,0);assert.equal(plan.overCapacity,true);assert.equal(plan.input.topics.length,1);assert.equal(plan.input.topics[0].source,'planner');
 await label('1日の学習可能時間（分）').fill('60');await button('計画を生成').click();await button('Study Planを保存').click();await page.reload();await page.waitForFunction(()=>document.querySelector('main fieldset')?.disabled===false);assert.equal(await label('Plannerの候補を使う').isChecked(),true);assert.equal(await label('Learning Memoryの候補を使う').isChecked(),false);
 const download=page.waitForEvent('download');await button('Export Study Plan').click();assert.equal(JSON.parse(fs.readFileSync(await (await download).path(),'utf8')).input.topics[0].topic,'Demo提出');
 await label('目標日').fill('2026-09-13');await button('計画を生成').click();assert.match(await page.locator('#plan-errors').innerText(),/期限/);await button('Clear all Study Plan').click();assert.equal(await saved('unipilot-study-plan-v1'),null);
 await page.goto(base+'/memory');await button('積分を削除').click();assert.equal((await saved('unipilot-learning-memory-v1')).items.length,0);await button('Clear all learning memory').click();assert.equal(await saved('unipilot-learning-memory-v1'),null);
 // All13 product routes and accessibility essentials at requested widths.
 for(const route of ['','study','materials','exam','report','research','sources','gpa','degree','planner','email','memory','plan']){await page.goto(base+'/'+route);await page.locator('main h1').waitFor();for(const width of [360,390,768,1024,1440]){await page.setViewportSize({width,height:950});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),route+'/'+width);layouts.push({route:route||'home',width,overflow:false});}}
 await page.goto(base+'/memory');await page.setViewportSize({width:390,height:950});const targets=await page.locator('main button,main .consent-row').evaluateAll(ns=>ns.map(n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height})));assert.ok(targets.every(t=>t.width>=44&&t.height>=44));
 assert.equal(await page.locator('input:not([type=checkbox]),textarea,select').evaluateAll(ns=>ns.every(n=>n.labels?.length>0)),true);assert.ok(await page.locator('[aria-live=polite]').count());await page.emulateMedia({reducedMotion:'reduce'});await page.keyboard.press('Tab');assert.notEqual(await page.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle),'none');
 assert.deepEqual(posts,[]);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'memory-plan-results.json'),JSON.stringify({gate:'PASS',layouts,checks:['consent','no silent save','memory add/edit/delete/clear/export','student confidence','provenance','weakness confirmation','plan capacity','zero availability','deadline rejection','out-of-order reschedule','memory opt-in/off','planner opt-in','local persistence','plan export/delete','Today saved only','labels','44px','focus','reduced motion'],pageErrors:errors,postRequests:posts,DEMO:'PASS',LIVE:'NOT_TESTED'},null,2)+'\n');await browser.close();console.log('PASS memory/plan workflows +75 responsive checks');
})().catch(e=>{console.error(e);process.exit(1);});
