from __future__ import annotations

from collections import Counter
import json
from pathlib import Path
import re


SPECIAL_TOKENS = ["<PAD>", "<BOS>", "<EOS>", "<UNK>", "<USER>", "<ASSISTANT>", "<SYSTEM>"]


class BPETokenizer:
    """Dependency-free byte-level BPE. Every UTF-8 string round-trips exactly."""

    def __init__(self):
        self.special_tokens = list(SPECIAL_TOKENS)
        self.token_bytes: dict[int, bytes] = {i + len(SPECIAL_TOKENS): bytes([i]) for i in range(256)}
        self.merges: list[tuple[int, int, int]] = []
        self._refresh()

    def _refresh(self) -> None:
        self.special_to_id = {token: i for i, token in enumerate(self.special_tokens)}
        self.merge_map = {(left, right): (rank, new) for rank, (left, right, new) in enumerate(self.merges)}

    @property
    def vocab_size(self) -> int:
        return len(self.special_tokens) + len(self.token_bytes)

    @property
    def pad_id(self): return self.special_to_id["<PAD>"]
    @property
    def bos_id(self): return self.special_to_id["<BOS>"]
    @property
    def eos_id(self): return self.special_to_id["<EOS>"]

    def train(self, texts: list[str], vocab_size: int = 512, min_frequency: int = 2) -> None:
        if vocab_size < len(self.special_tokens) + 256:
            raise ValueError("byte-level vocabulary requires at least 263 tokens")
        sequences = [list(text.encode("utf-8")) for text in texts if text]
        offset = len(self.special_tokens)
        sequences = [[value + offset for value in seq] for seq in sequences]
        self.merges = []
        self.token_bytes = {i + offset: bytes([i]) for i in range(256)}
        next_id = offset + 256
        while next_id < vocab_size:
            pairs = Counter((seq[i], seq[i + 1]) for seq in sequences for i in range(len(seq) - 1))
            if not pairs:
                break
            pair, frequency = pairs.most_common(1)[0]
            if frequency < min_frequency:
                break
            new_sequences = []
            for seq in sequences:
                merged, i = [], 0
                while i < len(seq):
                    if i + 1 < len(seq) and (seq[i], seq[i + 1]) == pair:
                        merged.append(next_id); i += 2
                    else:
                        merged.append(seq[i]); i += 1
                new_sequences.append(merged)
            sequences = new_sequences
            self.token_bytes[next_id] = self.token_bytes[pair[0]] + self.token_bytes[pair[1]]
            self.merges.append((pair[0], pair[1], next_id))
            next_id += 1
        self._refresh()

    def _encode_bytes(self, value: bytes) -> list[int]:
        ids = [byte + len(self.special_tokens) for byte in value]
        for left, right, new in self.merges:
            output, i = [], 0
            while i < len(ids):
                if i + 1 < len(ids) and ids[i] == left and ids[i + 1] == right:
                    output.append(new); i += 2
                else:
                    output.append(ids[i]); i += 1
            ids = output
        return ids

    def encode(self, text: str, add_bos: bool = False, add_eos: bool = False) -> list[int]:
        ids = [self.bos_id] if add_bos else []
        pattern = "(" + "|".join(re.escape(token) for token in self.special_tokens) + ")"
        for part in re.split(pattern, text):
            if not part:
                continue
            if part in self.special_to_id:
                ids.append(self.special_to_id[part])
            else:
                ids.extend(self._encode_bytes(part.encode("utf-8")))
        if add_eos:
            ids.append(self.eos_id)
        return ids

    def decode(self, ids: list[int], skip_special: bool = False) -> str:
        pieces: list[str] = []
        buffer = bytearray()
        def flush():
            if buffer:
                # Generated token streams can end midway through a UTF-8 character.
                # Valid encoded text still round-trips exactly; incomplete generated bytes are omitted.
                pieces.append(bytes(buffer).decode("utf-8", errors="ignore")); buffer.clear()
        for token_id in ids:
            if token_id < len(self.special_tokens):
                flush()
                if not skip_special:
                    pieces.append(self.special_tokens[token_id])
            elif token_id in self.token_bytes:
                buffer.extend(self.token_bytes[token_id])
            else:
                flush(); pieces.append("<UNK>")
        flush()
        return "".join(pieces)

    def save(self, path: str | Path) -> None:
        payload = {
            "format": "unipilot-byte-bpe-v1",
            "special_tokens": self.special_tokens,
            "merges": self.merges,
            "token_bytes_hex": {str(key): value.hex() for key, value in self.token_bytes.items()},
        }
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        Path(path).write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    @classmethod
    def load(cls, path: str | Path) -> "BPETokenizer":
        payload = json.loads(Path(path).read_text(encoding="utf-8"))
        instance = cls()
        instance.special_tokens = payload["special_tokens"]
        instance.merges = [tuple(item) for item in payload["merges"]]
        instance.token_bytes = {int(key): bytes.fromhex(value) for key, value in payload["token_bytes_hex"].items()}
        instance._refresh()
        return instance
